### ISSUE TITLE
Please do not install examples: they conflict with other packages

### ISSUE THREAD

**Issue by yurivict** [pavlin-policar/fastTSNE#45] opened 2018-12-15 09:15 UTC
```
Installing py36-fastTSNE-0.2.13...
pkg-static: py36-fastTSNE-0.2.13 conflicts with py36-tweepy-3.5.0 (installs files into the same place).  Problematic file: /usr/local/lib/python3.6/site-packages/examples/__init__.py
*** Error code 70
```
There is no need to install examples.

**Comment by pavlin-policar** [comment] 2018-12-15 09:44
Duplicate of #37.

**Closed by pavlin-policar** 2018-12-15 09:44 UTC
